### ISSUE TITLE
Disable quick reply -> no text bar in quick edit

### ISSUE THREAD

**Issue by Cu8eR** [martec/quickadveditor#3]
Text bar in quick edit is not shown when you disable quick reply window in user CP.

**Comment by martec** [comment]
i not have time now...
i will investigate when possible

**Comment by badboy4life91** [comment]
thanks for investigate

**Comment by martec** [comment]
sorry for slow reply...

open quickadveditor.php with notepad++

find:
if($mybb->settings['quickreply'] == 0)

replace with:
if(($mybb->settings['quickreply'] == 0) || ($mybb->user['showquickreply'] == 0))

And thanks to report... will fixed in next version.

**Comment by Cu8eR** [comment]
Yes, it works fine, Thank you!

**Comment by martec** [comment]
fixed in 6.1.2
