### ISSUE TITLE
Mycode Font disabled

### ISSUE THREAD

**Issue by CvH** [martec/quickadveditor#5]
If I disable **Allow Font MyCode** (_Setting this to yes allows users to use the Font MyCode._) in myBB settings and paste some copy into the post area witch include some kind of formatting I get it displayed as formatted text. 
If I click post it get posted as [font ...] text [/font] in clear text.

![picture](http://fs5.directupload.net/images/160323/8p5mw88r.png)

**Comment by martec** [comment]
http://community.mybb.com/thread-189827.html
